# Generated by Django 2.2 on 2019-04-30 19:47

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=orders.models.generateUUID, editable=False, max_length=36, unique=True),
        ),
    ]
