# Generated by Django 2.2 on 2019-05-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190506_2303'),
        ('products', '0003_auto_20190430_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='profiles',
            field=models.ManyToManyField(related_name='profiles', to='profiles.Profile'),
        ),
    ]
