# Generated by Django 2.2 on 2019-05-09 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='profiles',
            field=models.ManyToManyField(to='profiles.Profile'),
        ),
    ]
