# Generated by Django 2.2 on 2019-05-09 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20190509_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='profiles',
        ),
    ]
