# Generated by Django 2.2 on 2019-05-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20190506_2303'),
        ('products', '0006_remove_product_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to='profiles.Profile'),
        ),
    ]
