# Generated by Django 2.2 on 2019-05-12 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190511_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(null=True, related_name='users', to='profiles.Profile'),
        ),
    ]
