export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE'

export const FETCH_PRODUCT_BY_ID_START = 'FETCH_PRODUCT_BY_ID_START'
export const FETCH_PRODUCT_BY_ID_SUCCESS = 'FETCH_PRODUCT_BY_ID_SUCCESS'
export const FETCH_PRODUCT_BY_ID_FAILURE = 'FETCH_PRODUCT_BY_ID_FAILURE'

export const FETCH_PRODUCT_BY_SLUG_START = 'FETCH_PRODUCT_BY_SLUG_START'
export const FETCH_PRODUCT_BY_SLUG_SUCCESS = 'FETCH_PRODUCT_BY_SLUG_SUCCESS'
export const FETCH_PRODUCT_BY_SLUG_FAILURE = 'FETCH_PRODUCT_BY_SLUG_FAILURE'

export const FETCH_CATEGORIES_START = 'FETCH_CATEGORIES_START'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'

export const FETCH_USER_BY_ID_START = 'FETCH_USER_BY_ID_START'
export const FETCH_USER_BY_ID_SUCCESS = 'FETCH_USER_BY_ID_SUCCESS'
export const FETCH_USER_BY_ID_FAILURE = 'FETCH_USER_BY_ID_FAILURE'

export const FETCH_CABINET_START = 'FETCH_CABINET_START'
export const FETCH_CABINET_SUCCESS = 'FETCH_CABINET_SUCCESS'
export const FETCH_CABINET_FAILURE = 'FETCH_CABINET_FAILURE'

export const DELETE_USER_START = 'FETCH_USER_START'
export const DELETE_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const DELETE_USER_FAILURE = 'FETCH_USER_FAILURE'

export const LOGIN_USER_START = 'LOGIN_USER_START'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'

export const LOGOUT_USER_START = 'LOGOUT_USER_START'
export const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
export const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'

export const REGISTER_USER_START = 'REGISTER_USER_START'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE'

export const ADD_PRODUCT_TO_BASKET = 'ADD_PRODUCT_TO_BASKET'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const LIKE_PRODUCT = 'LIKE_PRODUCT'
export const SEARCH_PRODUCT = 'SEARCH_PRODUCT'
export const CLEAN_BASKET = 'CLEAN_BASKET'
export const GET_ERRORS = 'GET_ERRORS';
export const CREATE_MESSAGE = 'CREATE_MESSAGE';
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_USERS = 'CLEAR_USERS';
