# Generated by Django 2.2 on 2019-05-07 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20190506_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.Product'),
        ),
    ]
